/*DROP TABLE IF EXISTS `CALENDARIO`;
DROP TABLE IF EXISTS `CONFIGURACION`;
DROP TABLE IF EXISTS `PEDIDOS_PROVEEDORES_PROD`;
DROP TABLE IF EXISTS `PEDIDOS_PROVEEDORES`;
DROP TABLE IF EXISTS `PROVEEDORES`;
DROP TABLE IF EXISTS `PEDIDOS_PRODUCTOS`;
DROP TABLE IF EXISTS `PEDIDOS`;
DROP TABLE IF EXISTS `CONTABILIDAD`;
DROP TABLE IF EXISTS `PRODUCTOS_PACK`;
DROP TABLE IF EXISTS `PRODUCTOS`;
DROP TABLE IF EXISTS `SUBCATEGORIAS`;
DROP TABLE IF EXISTS `CATEGORIAS`;
DROP TABLE IF EXISTS `UNIDADES`;
DROP TABLE IF EXISTS `USUARIOS`;
DROP TABLE IF EXISTS `SOLICITUDES`;*/

CREATE TABLE USUARIOS
(
   `ID_USUARIO`       VARCHAR(5),
   `CLAVE`            VARCHAR(20) NOT NULL,
   `TIPO_USUARIO`     VARCHAR(20) DEFAULT 'USUARIO' NOT NULL,
   `NUMERO_USUARIO`   INTEGER(5) NOT NULL,
   `NOMBRE`           VARCHAR(100) NOT NULL,
   `APELLIDOS`        VARCHAR(120) NOT NULL,
   `EMAIL`            VARCHAR(120) NOT NULL,
   `DIRECCION`        VARCHAR(255),
   `TFNO_CONTACTO`    NUMERIC(9, 0),
   `TFNO_MOVIL`       NUMERIC(9, 0),
   `WTS_APP`          BOOLEAN NOT NULL,
   `CODIGO_POSTAL`    NUMERIC(5, 0),
   `POBLACION`        VARCHAR(100),
   `PROVINCIA`        VARCHAR(50),
   `FECHA_ALTA`       DATE,
   `ACTIVO`           BOOLEAN DEFAULT '1' NOT NULL,
   `SALDO`            NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
   `NIF`			  VARCHAR(10),
   PRIMARY KEY(`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE USUARIOS MODIFY `NUMERO_USUARIO` INT AUTO_INCREMENT UNIQUE KEY;

CREATE TABLE CATEGORIAS
(
   `ID_CATEGORIA`   INTEGER(3) AUTO_INCREMENT,
   `DESCRIPCION`    VARCHAR(50) NOT NULL,
   `RECARGO`        DECIMAL(5, 2) DEFAULT 0 NOT NULL,
   `ACTIVO`         BOOLEAN DEFAULT '1' NOT NULL,
   PRIMARY KEY(`ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE SUBCATEGORIAS
(
   `ID_SUBCATEGORIA`   INTEGER(10) AUTO_INCREMENT,
   `ID_CATEGORIA`      INT(10),
   `DESCRIPCION`       VARCHAR(255) NOT NULL,
   `RECARGO`           DECIMAL(5, 2) DEFAULT 0 NOT NULL,
   `ACTIVO`            BOOLEAN DEFAULT '1' NOT NULL,
   PRIMARY KEY(`ID_SUBCATEGORIA`)
);

ALTER TABLE SUBCATEGORIAS ADD CONSTRAINT `FK_SUBCATEGORIAS_CATEG` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES CATEGORIAS(`ID_CATEGORIA`);

CREATE TABLE UNIDADES
(
   `ID_UNIDAD`     INTEGER(10) AUTO_INCREMENT,
   `DESCRIPCION`   VARCHAR(25) NOT NULL,
   PRIMARY KEY(`ID_UNIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE PRODUCTOS
(
   `ID_PRODUCTO`     INTEGER(10) AUTO_INCREMENT,
   `ID_CATEGORIA`    INT(10) NOT NULL,
   `ID_SUBCATEGORIA` INT(10) NOT NULL,
   `DESCRIPCION`     VARCHAR(100) NOT NULL,
   `PRECIO`          DOUBLE(6, 2) NOT NULL,
   `DESCRIPCION_MEDIDA` VARCHAR(100),
   `UNIDAD_MEDIDA`   INTEGER(10) NOT NULL,
   `RECARGO`         DOUBLE(5, 2),
   `ACTIVO`          BOOLEAN DEFAULT '1' NOT NULL,
   `FOTO`            BLOB,
   `PROVEEDOR_1`     VARCHAR(20) NOT NULL,
   `CANTIDAD_1`      DECIMAL(10, 2) DEFAULT 0 NOT NULL,
   `PROVEEDOR_2`     VARCHAR(20) NOT NULL,
   `CANTIDAD_2`      DECIMAL(10, 2) DEFAULT 0 NOT NULL,
   `CANTIDAD_ILIMITADA` BOOLEAN DEFAULT '1' NOT NULL,
   `INC_CUARTOS`     BOOLEAN DEFAULT '0' NOT NULL,
   PRIMARY KEY(`ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE PRODUCTOS ADD CONSTRAINT `FK_PROD_CATEG` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES CATEGORIAS(`ID_CATEGORIA`);
ALTER TABLE PRODUCTOS ADD CONSTRAINT `FK_UNIDAD_MEDIDA` FOREIGN KEY (`UNIDAD_MEDIDA`) REFERENCES UNIDADES(`ID_UNIDAD`);
ALTER TABLE PRODUCTOS ADD CONSTRAINT `FK_PRODUCT_SUBCAT` FOREIGN KEY (`ID_SUBCATEGORIA`) REFERENCES SUBCATEGORIAS(`ID_SUBCATEGORIA`);

CREATE TABLE CALENDARIO
(
   `ID_CALENDARIO`   int(10) AUTO_INCREMENT,
   `ID_CATEGORIA`    int(10),
   `FECHA_PEDIDO`    date,
   `FECHA_ENTREGA`   date,
   `ESTADO`          varchar(20) DEFAULT "'EN TRAMITACIÓN'",
   PRIMARY KEY (`ID_CALENDARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE CALENDARIO ADD CONSTRAINT `fk_cal_categ` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES CATEGORIAS (`ID_CATEGORIA`);


CREATE TABLE CONFIGURACION
(
   `PARAMETRO`      VARCHAR(30) NOT NULL,
   `VALOR`   VARCHAR(255),
   PRIMARY KEY(`PARAMETRO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


CREATE TABLE PROVEEDORES
(
   `ID_PROVEEDOR`    INTEGER(10) AUTO_INCREMENT,
   `NOMBRE`          VARCHAR(50) NOT NULL,
   `DESCRIPCION`     VARCHAR(100),
   `REPRESENTANTE`   VARCHAR(100),
   `EMAIL`           VARCHAR(100),
   `TELEFONO`        VARCHAR(20),
   `FECHA_ALTA`      DATE,
   `PEDIDO_PROCESADO` BOOLEAN DEFAULT '0' NOT NULL,
   `TOTAL_REVISADO`	 NUMERIC(8, 2),
   PRIMARY KEY(`ID_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE PEDIDOS
(
   `ID_PEDIDO`      INTEGER(10) AUTO_INCREMENT,
   `ID_USUARIO`     VARCHAR(5) NOT NULL,
   `LOTE`           VARCHAR(255) NOT NULL,
   `FECHA_PEDIDO`   DATETIME NOT NULL,
   `ESTADO`			VARCHAR(20) DEFAULT 'PREPARACION' NOT NULL,
   PRIMARY KEY(`ID_PEDIDO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE PEDIDOS ADD CONSTRAINT `FK_PEDIDOS_USU` FOREIGN KEY (`ID_USUARIO`) REFERENCES USUARIOS (`ID_USUARIO`);

CREATE TABLE PEDIDOS_PRODUCTOS (
	`ID_PEDIDO` INT(10), 
	`ID_PRODUCTO` INT(10), 
	`PRECIO` DOUBLE(6,2) NOT NULL, 
	`CANTIDAD` DECIMAL(6,2) NOT NULL, 
	`CANTIDAD_REVISADA` DECIMAL(6,2),
	PRIMARY KEY (`ID_PEDIDO`, `ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;     
                                                                                                                                                                                                                                                                       
ALTER TABLE PEDIDOS_PRODUCTOS ADD CONSTRAINT `FK_PEDIDOS_PRODUCTOS` FOREIGN KEY (`ID_PEDIDO`) REFERENCES PEDIDOS (`ID_PEDIDO`);
ALTER TABLE PEDIDOS_PRODUCTOS ADD CONSTRAINT `FK_PEDIDOS_PRODUCTOS2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES PRODUCTOS (`ID_PRODUCTO`);

CREATE TABLE CONTABILIDAD
(
   `ID_APUNTE`    INTEGER(10) AUTO_INCREMENT,
   `FECHA`        DATETIME NOT NULL,
   `CONCEPTO`     VARCHAR(255) NOT NULL,
   `USUARIO`	  VARCHAR(10) DEFAULT '-SISTEMA-' NOT NULL,
   `AUTOMATICA`   BOOLEAN DEFAULT '1' NOT NULL,
   `IMPORTE`      NUMERIC(6, 2) DEFAULT 0 NOT NULL,
   `ESDEBE`       BOOLEAN DEFAULT '1' NOT NULL,
   `TOTAL_CAJA`   NUMERIC(8, 2) DEFAULT 0 NOT NULL,
   PRIMARY KEY(`ID_APUNTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE PEDIDOS_PROVEEDORES
(
   `ID_PEDIDO_PROVEEDOR`   INTEGER(10) AUTO_INCREMENT NOT NULL,
   `ID_PROVEEDOR`          INT(10) NOT NULL,
   `LOTE`           	   VARCHAR(255) NOT NULL,
   `PEDIDO_PROCESADO`      BOOLEAN DEFAULT '0' NOT NULL,
   `TOTAL_REVISADO`    	   NUMERIC(8, 2),
   PRIMARY KEY(`ID_PEDIDO_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE PEDIDOS_PROVEEDORES ADD CONSTRAINT `FK_PEDIDOS_PROVEEDORES_PROV` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES PROVEEDORES(`ID_PROVEEDOR`);
ALTER TABLE PEDIDOS_PROVEEDORES ADD CONSTRAINT UNIQUE_PROV_LOTE UNIQUE (ID_PROVEEDOR, LOTE);

CREATE TABLE PEDIDOS_PROVEEDORES_PROD
(
   `ID_PEDIDO_PROVEEDOR`   INT(10),
   `ID_PRODUCTO`           INT(10),
   `PRECIO` 			   DOUBLE(6,2) NOT NULL,
   `CANTIDAD`   	 	   NUMERIC(6, 2) NOT NULL,
   `CANTIDAD_REV` 		   NUMERIC(8, 2) DEFAULT NULL,
   PRIMARY KEY(`ID_PEDIDO_PROVEEDOR`, `ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE PEDIDOS_PROVEEDORES_PROD ADD CONSTRAINT `FK_PEDIDOS_PROVEEDORES_PROD_1` FOREIGN KEY (`ID_PEDIDO_PROVEEDOR`) REFERENCES PEDIDOS_PROVEEDORES(`ID_PEDIDO_PROVEEDOR`);
ALTER TABLE PEDIDOS_PROVEEDORES_PROD ADD CONSTRAINT `FK_PEDIDOS_PROVEEDORES_PROD_2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES PRODUCTOS (`ID_PRODUCTO`);


CREATE TABLE CONTABILIDAD_USUARIO
(
   `FECHA`        DATETIME NOT NULL,
   `USUARIO`	  VARCHAR(10) NOT NULL,
   `CONCEPTO`     VARCHAR(255) NOT NULL,
   `IMPORTE`      NUMERIC(6, 2) NOT NULL,
   `ESDEBE`       BOOLEAN DEFAULT '1' NOT NULL,
   `TOTAL_SALDO`   NUMERIC(8, 2) NOT NULL,
   PRIMARY KEY(`FECHA`, `USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*nuevos cambios*/

/*
DELETE FROM CONTABILIDAD WHERE USUARIO<>'-SISTEMA-' AND ESDEBE=1;
UPDATE PEDIDOS_PRODUCTOS SET CANTIDAD_REVISADA = NULL WHERE CANTIDAD_REVISADA=0;
*/

/* Nuevos campos para PRODUCTOS */
ALTER TABLE PRODUCTOS ADD COLUMN `NOVEDAD` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `OFERTA` BOOLEAN DEFAULT '0' NOT NULL;

/* Nueva tabla */
CREATE TABLE PRODUCTOS_PACK
(
   `ID_PRODUCTO_PACK`     INTEGER(10) AUTO_INCREMENT,
   `ID_PRODUCTO`     INT(10) NOT NULL,
   PRIMARY KEY(`ID_PRODUCTO_PACK`, `ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
ALTER TABLE PRODUCTOS_PACK ADD CONSTRAINT `FK_PROD_P1` FOREIGN KEY (`ID_PRODUCTO_PACK`) REFERENCES PRODUCTOS(`ID_PRODUCTO`);
ALTER TABLE PRODUCTOS_PACK ADD CONSTRAINT `FK_PROD_P2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES PRODUCTOS(`ID_PRODUCTO`);

/* nueva tabla solicitudes */
CREATE TABLE SOLICITUDES
(
   `ID_SOLICITUD`     INTEGER(10) AUTO_INCREMENT NOT NULL,
   `TIPO_SOLICITUD`	  VARCHAR(15) NOT NULL,
   `FECHA_SOLICITUD`  DATE NOT NULL,
   `NOMBRE`           VARCHAR(100) NOT NULL,
   `APELLIDOS`        VARCHAR(120) NOT NULL,
   `NIF`			  VARCHAR(10) NOT NULL,
   `EMAIL`            VARCHAR(120) NOT NULL,
   `TFNO_CONTACTO`    NUMERIC(9, 0) NOT NULL,
   `OBSERVACIONES`    VARCHAR(1000) NOT NULL,
   `LEIDO`            BOOLEAN DEFAULT '0' NOT NULL,
   PRIMARY KEY(`ID_SOLICITUD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/* 09-06-2014 */
INSERT INTO CONFIGURACION (PARAMETRO, VALOR) VALUES ('F_CALC_SALDO_USUARIOS', '2014-06-11 00:00:00');

/* 10-06-2014 -*/
ALTER TABLE PRODUCTOS ADD COLUMN `ECOLOGICO` BOOLEAN DEFAULT '1' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `DESCRIPCION_LARGA` VARCHAR(255);

CREATE TABLE SUBGRUPOS
(
   `ID_SUBGRUPO`     INTEGER(10) AUTO_INCREMENT NOT NULL,
   `NOMBRE`           VARCHAR(255) NOT NULL,
   PRIMARY KEY(`ID_SUBGRUPO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

INSERT INTO SUBGRUPOS (ID_SUBGRUPO, NOMBRE) VALUES (1, 'CerroViejo - Sevilla');
INSERT INTO SUBGRUPOS (ID_SUBGRUPO, NOMBRE) VALUES (2, 'CerroViejo - Mairena');
INSERT INTO SUBGRUPOS (ID_SUBGRUPO, NOMBRE) VALUES (3, 'CerroViejo - Cazalla');

ALTER TABLE USUARIOS ADD COLUMN `ID_SUBGRUPO` INTEGER(10) DEFAULT '1' NOT NULL;
ALTER TABLE USUARIOS ADD CONSTRAINT `FK_USU_SUBGRUPO` FOREIGN KEY (`ID_SUBGRUPO`) REFERENCES SUBGRUPOS(`ID_SUBGRUPO`);
ALTER TABLE PRODUCTOS_PACK ADD COLUMN `CANTIDAD` INTEGER(3) DEFAULT '1' NOT NULL;

/* 10-07-2014 */
CREATE OR REPLACE VIEW CATALOGO_PRODUCTOS AS
select C.DESCRIPCION AS CATEGORIA,S.DESCRIPCION AS SUBCATEGORIA, PV.NOMBRE AS PROVEEDOR, P.DESCRIPCION, P.PRECIO, P.ID_PRODUCTO
			from PRODUCTOS P, CATEGORIAS C, SUBCATEGORIAS S, PROVEEDORES PV
			WHERE P.ID_CATEGORIA=C.ID_CATEGORIA AND P.ID_SUBCATEGORIA=S.ID_SUBCATEGORIA  AND P.PROVEEDOR_1 = PV.ID_PROVEEDOR AND P.ACTIVO='1'
			ORDER BY CATEGORIA, SUBCATEGORIA, DESCRIPCION;
			
/* 15-07-2014 */
ALTER TABLE PRODUCTOS ADD COLUMN `PESO_POR_UNIDAD` NUMERIC(6, 2) DEFAULT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `PESO_POR_UNIDAD` NUMERIC(6, 2) DEFAULT NULL;

/* 23-07-2014 */
ALTER TABLE PRODUCTOS ADD COLUMN `VEGANO` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `SIN_GLUTEN` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `COMERCIO_JUSTO` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `KM0` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `PROVINCIA` VARCHAR(30) NULL;

/* 01-08-2014 */
ALTER TABLE PRODUCTOS MODIFY DESCRIPCION_LARGA TEXT;

/* 11-08-2014 */
ALTER TABLE PEDIDOS ADD COLUMN `COMENTARIOS` VARCHAR(300) NULL;

/*15-08-2014 */
CREATE OR REPLACE VIEW VW_DEMANDA_X_USUARIO AS
SELECT S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, PO.DESCRIPCION AS PRODUCTO, 
	 SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA))  AS CANTIDAD_TOTAL,
	 SUM((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA)) * PP.PRECIO) AS COSTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND U.ACTIVO='1'
	AND (PP.CANTIDAD_REVISADA IS NULL OR PP.CANTIDAD_REVISADA > 0)
	GROUP BY S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION
	ORDER BY S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION; 


CREATE OR REPLACE VIEW VW_DEMANDA_X_USUARIO_LOTE AS
SELECT P.LOTE, S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, PO.DESCRIPCION AS PRODUCTO, 
	 SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA))  AS CANTIDAD_TOTAL,
	 SUM((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA)) * PP.PRECIO) AS COSTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND U.ACTIVO='1'
	GROUP BY P.LOTE, S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION
	ORDER BY ABS(P.LOTE), S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION; 


CREATE OR REPLACE VIEW VW_PRODUCTOS_MAS_DEMANDADOS AS
SELECT PO.DESCRIPCION AS PRODUCTO, 
	 SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA))  AS CANTIDAD_TOTAL
FROM PEDIDOS_PRODUCTOS PP, PRODUCTOS PO
WHERE PP.ID_PRODUCTO = PO.ID_PRODUCTO
AND (PP.CANTIDAD_REVISADA IS NULL OR PP.CANTIDAD_REVISADA>0)
	GROUP BY PO.DESCRIPCION
	ORDER BY CANTIDAD_TOTAL DESC; 
	
	
CREATE OR REPLACE VIEW VW_DEMANDA_A_PROVEDORES AS
SELECT P.NOMBRE AS PROVEEDOR, PRO.DESCRIPCION,  
	SUM(IF(PPP.CANTIDAD_REV is null, PPP.CANTIDAD, PPP.CANTIDAD_REV))  AS CANTIDAD_TOTAL, 
	SUM((IF(PPP.CANTIDAD_REV is null, PPP.CANTIDAD, PPP.CANTIDAD_REV)*PPP.PRECIO)) AS COSTO
FROM PROVEEDORES P, PEDIDOS_PROVEEDORES PP, PEDIDOS_PROVEEDORES_PROD PPP, PRODUCTOS PRO
WHERE PP.ID_PROVEEDOR = P.ID_PROVEEDOR
AND PP.ID_PEDIDO_PROVEEDOR = PPP.ID_PEDIDO_PROVEEDOR
AND PPP.ID_PRODUCTO = PRO.ID_PRODUCTO
AND PP.PEDIDO_PROCESADO=1
AND (PPP.CANTIDAD_REV IS NULL OR PPP.CANTIDAD_REV>0)
GROUP BY P.NOMBRE, PRO.DESCRIPCION
ORDER BY P.NOMBRE ASC, CANTIDAD DESC;

CREATE OR REPLACE VIEW VW_CONSUMO_X_USUARIO AS
SELECT S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, P.LOTE, 
	 SUM((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, PP.CANTIDAD_REVISADA)) * PP.PRECIO) AS GASTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND U.ACTIVO='1'
	GROUP BY S.NOMBRE, U.ID_USUARIO, P.LOTE
	ORDER BY S.NOMBRE, U.ID_USUARIO, ABS(P.LOTE);
	
/*09/09/2014*/
ALTER TABLE PRODUCTOS ADD COLUMN `DEPENDE_CESTA` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `PRECIO_CESTA_1` DECIMAL(5, 2);
ALTER TABLE PRODUCTOS ADD COLUMN `PRECIO_CESTA_2` DECIMAL(5, 2);
ALTER TABLE PRODUCTOS ADD COLUMN `PRECIO_1` DECIMAL(5, 2);
ALTER TABLE PRODUCTOS ADD COLUMN `PRECIO_2` DECIMAL(5, 2);
ALTER TABLE PRODUCTOS ADD COLUMN `PRECIO_3` DECIMAL(5, 2);

INSERT INTO CATEGORIAS (ID_CATEGORIA, DESCRIPCION, ACTIVO) VALUES ('-10', 'Productos Generales', '1');
INSERT INTO SUBCATEGORIAS (ID_CATEGORIA, ID_SUBCATEGORIA, DESCRIPCION) VALUES ('-10', '-10', 'Transporte');

/*07/10/2014*/
CREATE OR REPLACE VIEW CATALOGO_PRODUCTOS AS
select C.DESCRIPCION AS CATEGORIA,S.DESCRIPCION AS SUBCATEGORIA, PV.NOMBRE AS PROVEEDOR, P.DESCRIPCION, P.PRECIO, P.ID_PRODUCTO, U.DESCRIPCION AS MEDIDA, P.DESCRIPCION_MEDIDA
			from PRODUCTOS P, CATEGORIAS C, SUBCATEGORIAS S, PROVEEDORES PV, UNIDADES U
			WHERE P.ID_CATEGORIA=C.ID_CATEGORIA AND P.ID_SUBCATEGORIA=S.ID_SUBCATEGORIA  AND P.PROVEEDOR_1 = PV.ID_PROVEEDOR AND P.ACTIVO='1' AND P.UNIDAD_MEDIDA=U.ID_UNIDAD
			ORDER BY CATEGORIA, SUBCATEGORIA, DESCRIPCION;

/*08/10/2014*/
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `CHECK_REVISADO` BOOLEAN DEFAULT '0' NOT NULL;

INSERT INTO SUBGRUPOS (ID_SUBGRUPO, NOMBRE) VALUES (-1, 'Los pollitos');

/*14/10/2014*/
ALTER TABLE PRODUCTOS ADD COLUMN `SIN_LACTOSA` BOOLEAN DEFAULT '0' NOT NULL;

/*15/10/2014*/
ALTER TABLE PEDIDOS ADD COLUMN `HORA_INI` VARCHAR(5);
ALTER TABLE PEDIDOS ADD COLUMN `HORA_FIN` VARCHAR(5);

/*27/10/2014*/
ALTER TABLE PRODUCTOS ADD COLUMN `GOURMET` BOOLEAN DEFAULT '0' NOT NULL;

ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `PRECIO_SIN_RECARGO` DECIMAL(6, 2) DEFAULT 0 NOT NULL;

ALTER TABLE PRODUCTOS MODIFY COLUMN `PROVEEDOR_1`     INTEGER(10) NOT NULL;
ALTER TABLE PRODUCTOS MODIFY COLUMN `PROVEEDOR_2`     INTEGER(10) NOT NULL;
ALTER TABLE PRODUCTOS ADD CONSTRAINT `FK_PROV1` FOREIGN KEY (`PROVEEDOR_1`) REFERENCES PROVEEDORES(`ID_PROVEEDOR`);
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `PROVEEDOR_1`        INTEGER(10) NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `CANTIDAD_1`         DECIMAL(10, 2) DEFAULT 0 NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `PROVEEDOR_2`        INTEGER(10) NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `CANTIDAD_2`         DECIMAL(10, 2) DEFAULT 0 NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `CANTIDAD_ILIMITADA` BOOLEAN DEFAULT '1' NOT NULL;

/*DROP TABLE VW_DEMANDA_X_USUARIO;*/
CREATE OR REPLACE VIEW VW_DEMANDA_X_USUARIO AS
SELECT S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, PO.DESCRIPCION AS PRODUCTO, 
	 ROUND(SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))), 2) AS CANTIDAD_TOTAL,
	 SUM(ROUND((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))) * PP.PRECIO, 2)) AS COSTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND U.ACTIVO='1'
	AND (PP.CANTIDAD_REVISADA IS NULL OR PP.CANTIDAD_REVISADA > 0)
	GROUP BY S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION
	ORDER BY S.NOMBRE, U.ID_USUARIO, PO.DESCRIPCION; 

/*DROP TABLE VW_DEMANDA_X_USUARIO_LOTE;*/
CREATE OR REPLACE VIEW VW_DEMANDA_X_USUARIO_LOTE AS
SELECT P.LOTE, P.ID_PEDIDO, S.ID_SUBGRUPO, S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, PR.NOMBRE as PROVEEDOR, PO.DESCRIPCION AS PRODUCTO, 
	 ROUND(SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))), 2) AS CANTIDAD_TOTAL,
	 SUM(ROUND((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))) * PP.PRECIO, 2)) AS COSTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S, PROVEEDORES PR
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND PO.PROVEEDOR_1 = PR.ID_PROVEEDOR
	AND U.ACTIVO='1'
	GROUP BY P.LOTE, P.ID_PEDIDO, S.ID_SUBGRUPO, S.NOMBRE, U.ID_USUARIO, PR.NOMBRE, PO.DESCRIPCION
	ORDER BY ABS(P.LOTE), S.NOMBRE, U.ID_USUARIO, PR.NOMBRE, PO.DESCRIPCION; 

/*DROP TABLE VW_PRODUCTOS_MAS_DEMANDADOS;*/
CREATE OR REPLACE VIEW VW_PRODUCTOS_MAS_DEMANDADOS AS
SELECT PO.DESCRIPCION AS PRODUCTO, 
	 ROUND(SUM((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA)))), 2) AS CANTIDAD_TOTAL
FROM PEDIDOS_PRODUCTOS PP, PRODUCTOS PO
WHERE PP.ID_PRODUCTO = PO.ID_PRODUCTO
AND (PP.CANTIDAD_REVISADA IS NULL OR PP.CANTIDAD_REVISADA>0)
	GROUP BY PO.DESCRIPCION
	ORDER BY CANTIDAD_TOTAL DESC; 
	
/*DROP TABLE VW_CONSUMO_X_USUARIO;*/
CREATE OR REPLACE VIEW VW_CONSUMO_X_USUARIO AS
SELECT S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, P.LOTE, 
	 SUM(ROUND((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))) * PP.PRECIO, 2)) AS GASTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND U.ACTIVO='1'
	GROUP BY S.NOMBRE, U.ID_USUARIO, P.LOTE
	ORDER BY S.NOMBRE, U.ID_USUARIO, ABS(P.LOTE);

/* 11/11/2014 */
CREATE OR REPLACE VIEW VW_DEMANDA_X_USUARIO_LOTE AS
SELECT P.LOTE, P.ID_PEDIDO, S.ID_SUBGRUPO, S.NOMBRE AS SUBGRUPO, U.ID_USUARIO AS USUARIO, PR.NOMBRE as PROVEEDOR, PO.ID_PRODUCTO, PO.DESCRIPCION AS PRODUCTO, 
	 ROUND(SUM(IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))), 2) AS CANTIDAD_TOTAL,
	 SUM(ROUND((IF(PP.CANTIDAD_REVISADA is null, PP.CANTIDAD, 
	 	IF (PP.PESO_POR_UNIDAD > 0 , (PP.CANTIDAD_REVISADA / PP.PESO_POR_UNIDAD), PP.CANTIDAD_REVISADA))) * PP.PRECIO, 2)) AS COSTO
FROM PEDIDOS_PRODUCTOS PP, PEDIDOS P, PRODUCTOS PO, USUARIOS U, SUBGRUPOS S, PROVEEDORES PR
WHERE PP.ID_PEDIDO = P.ID_PEDIDO
	AND PP.ID_PRODUCTO = PO.ID_PRODUCTO
	AND P.ID_USUARIO = U.ID_USUARIO
	AND U.ID_SUBGRUPO=S.ID_SUBGRUPO
	AND PO.PROVEEDOR_1 = PR.ID_PROVEEDOR
	AND U.ACTIVO='1'
	GROUP BY P.LOTE, P.ID_PEDIDO, S.ID_SUBGRUPO, S.NOMBRE, U.ID_USUARIO, PR.NOMBRE, PO.ID_PRODUCTO, PO.DESCRIPCION
	ORDER BY ABS(P.LOTE), S.NOMBRE, U.ID_USUARIO, PR.NOMBRE, PO.DESCRIPCION; 
	
/* 11/11/2014 */
ALTER TABLE PRODUCTOS ADD COLUMN `PEDIDO_MINIMO` DECIMAL(5, 2) DEFAULT 0 NOT NULL;

/* 16/11/2014 */
CREATE TABLE VOTACIONES
(
   `ID`    INTEGER(10),
   `VOTOS` INTEGER(10) NOT NULL,
   `VALOR` INTEGER(10) NOT NULL,
   PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/* 24/11/2014 */
ALTER TABLE PRODUCTOS ADD COLUMN `IMPORTE_SIN_IVA` DOUBLE(6, 2) DEFAULT 0 NOT NULL;
ALTER TABLE PRODUCTOS ADD COLUMN `TIPO_IVA` DOUBLE(5, 2) DEFAULT 0 NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `IMPORTE_SIN_IVA` DOUBLE(6, 2) DEFAULT 0 NOT NULL;
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `TIPO_IVA` DOUBLE(5, 2) DEFAULT 0 NOT NULL;

/* 27/11/2014 */
CREATE OR REPLACE VIEW VW_MAXFECHA_CONT_USUARIO AS
select MAX(FECHA) as FECHA, USUARIO from CONTABILIDAD_USUARIO GROUP BY USUARIO;

CREATE OR REPLACE VIEW VW_ERRORES_SALDO_USUARIOS AS
select c1.TOTAL_SALDO, u.SALDO, c2.FECHA, c1.USUARIO from CONTABILIDAD_USUARIO c1, VW_MAXFECHA_CONT_USUARIO c2, USUARIOS u
where c1.FECHA = c2.FECHA
and c1.USUARIO = c2.USUARIO
and c2.USUARIO = u.ID_USUARIO
and c1.TOTAL_SALDO <> u.SALDO
order by c1.USUARIO;

ALTER TABLE USUARIOS ADD COLUMN `DESCUENTO_RECARGO` INTEGER(3) DEFAULT 0 NOT NULL;
ALTER TABLE PEDIDOS ADD COLUMN `DESCUENTO_RECARGO` INTEGER(3) DEFAULT 0 NOT NULL;

/* 15/12/2014 */
ALTER TABLE PRODUCTOS DROP COLUMN FOTO;

ALTER TABLE PEDIDOS  ADD COLUMN `COBRADO` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE USUARIOS  ADD COLUMN `RECARGO_EQ` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE USUARIOS  ADD COLUMN `VER_FACTURA` BOOLEAN DEFAULT '0' NOT NULL;

ALTER TABLE PEDIDOS  ADD COLUMN `NUM_ALBARAN` INTEGER(4);
ALTER TABLE PEDIDOS  ADD COLUMN `NUM_FACTURA` INTEGER(4);
ALTER TABLE PEDIDOS  ADD COLUMN `FECHA_FACTURA` date;

CREATE OR REPLACE VIEW CATALOGO_PRODUCTOS AS
select C.DESCRIPCION AS CATEGORIA,S.DESCRIPCION AS SUBCATEGORIA, PV.NOMBRE AS PROVEEDOR, P.DESCRIPCION, P.PRECIO, P.IMPORTE_SIN_IVA, P.TIPO_IVA, P.ID_PRODUCTO, U.DESCRIPCION AS MEDIDA, P.DESCRIPCION_MEDIDA
			from PRODUCTOS P, CATEGORIAS C, SUBCATEGORIAS S, PROVEEDORES PV, UNIDADES U
			WHERE P.ID_CATEGORIA=C.ID_CATEGORIA AND P.ID_SUBCATEGORIA=S.ID_SUBCATEGORIA  AND P.PROVEEDOR_1 = PV.ID_PROVEEDOR AND P.ACTIVO='1' AND P.UNIDAD_MEDIDA=U.ID_UNIDAD
			ORDER BY CATEGORIA, SUBCATEGORIA, DESCRIPCION;
			
ALTER TABLE PEDIDOS  ADD COLUMN `RE` BOOLEAN DEFAULT '0' NOT NULL;
ALTER TABLE PEDIDOS  ADD COLUMN `FECHA_ENTREGA` date;

/* 15/02/2015 */
CREATE TABLE LISTAS
(
   `ID_LISTA`       INTEGER(10) AUTO_INCREMENT,
   `ID_USUARIO`     VARCHAR(5) NOT NULL,
   `NOMBRE`			VARCHAR(100) NOT NULL,
   PRIMARY KEY(`ID_LISTA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE LISTAS ADD CONSTRAINT `FK_LISTAS_USU` FOREIGN KEY (`ID_USUARIO`) REFERENCES USUARIOS (`ID_USUARIO`);

CREATE TABLE LISTAS_PRODUCTOS (
	`ID_LISTA` INT(10), 
	`ID_PRODUCTO` INT(10), 
	`CANTIDAD` DECIMAL(6,2) NOT NULL, 
	PRIMARY KEY (`ID_LISTA`, `ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;     
                                                                                                                                                                                                                                                                       
ALTER TABLE LISTAS_PRODUCTOS ADD CONSTRAINT `FK_LISTAS_PRODUCTOS` FOREIGN KEY (`ID_LISTA`) REFERENCES LISTAS (`ID_LISTA`);
ALTER TABLE LISTAS_PRODUCTOS ADD CONSTRAINT `FK_LISTAS_PRODUCTOS2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES PRODUCTOS (`ID_PRODUCTO`);

/* 06/04/2015 pedidos prov por subgrupos */ 
ALTER TABLE PEDIDOS_PROVEEDORES ADD COLUMN ID_SUBGRUPO	int(10) DEFAULT NULL;
// ALTER TABLE PEDIDOS_PROVEEDORES ADD CONSTRAINT `FK_PEDIDOS_PROVEEDORES_SUBG` FOREIGN KEY (`ID_SUBGRUPO`) REFERENCES SUBGRUPOS (`ID_SUBGRUPO`);
ALTER TABLE PEDIDOS_PROVEEDORES DROP INDEX UNIQUE_PROV_LOTE;
ALTER TABLE PEDIDOS_PROVEEDORES ADD CONSTRAINT UNIQUE_PROV_LOTE UNIQUE (ID_PROVEEDOR, LOTE, ID_SUBGRUPO);
ALTER TABLE PEDIDOS_PROVEEDORES ADD COLUMN ENVIADO int(1) DEFAULT 0;

/* 30/08/2015 */
ALTER TABLE PEDIDOS_PRODUCTOS ADD COLUMN `CHECK_FINALIZADO` BOOLEAN DEFAULT '0' NOT NULL;

CREATE TABLE CLASE_PRODUCTO
(
   `ID_CLASE_PRODUCTO`   INTEGER(10),
   `ID_CATEGORIA`      INTEGER(10),
   `ID_SUBCATEGORIA`   INTEGER(10),
   `DESCRIPCION`       VARCHAR(255) NOT NULL,
   `SECUENCIA`   INTEGER(5) NOT NULL DEFAULT 0,
   `ACTIVO`            BOOLEAN DEFAULT '1' NOT NULL,
   PRIMARY KEY(`ID_CLASE_PRODUCTO`)
);

ALTER TABLE PRODUCTOS  ADD COLUMN `ID_CLASE_PRODUCTO` INTEGER(10);

/*ALTER TABLE CLASE_PRODUCTO ADD CONSTRAINT `FK_CLASE_PRODUCTO_SUBCAT` FOREIGN KEY (`ID_SUBCATEGORIA`) REFERENCES SUBCATEGORIAS(`ID_SUBCATEGORIA`);
ALTER TABLE CLASE_PRODUCTO ADD CONSTRAINT `FK_CLASE_PRODUCTO_CAT` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES SUBCATEGORIAS(`ID_CATEGORIA`);*/

/* 18/10/2015 */
ALTER TABLE `CONTABILIDAD` CHANGE `TOTAL_CAJA` `TOTAL_CAJA` DECIMAL(10,2) NOT NULL DEFAULT '0.00';
ALTER TABLE `CONTABILIDAD` CHANGE `IMPORTE` `IMPORTE` DECIMAL(7,2) NOT NULL DEFAULT '0.00';
ALTER TABLE `CONTABILIDAD_USUARIO` CHANGE `TOTAL_SALDO` `TOTAL_SALDO`  DECIMAL(10,2) NOT NULL;
ALTER TABLE `CONTABILIDAD_USUARIO` CHANGE `IMPORTE` `IMPORTE` DECIMAL(7,2) NOT NULL;
ALTER TABLE `USUARIOS` CHANGE `SALDO` `SALDO` DECIMAL(7,2) NOT NULL DEFAULT '0.00';

/* 04/01/2016 */
CREATE TABLE HORARIOS
(
   `ID_HORARIO`   INTEGER(5) AUTO_INCREMENT,
   `HORA_INI`       VARCHAR(5) NOT NULL,
   `HORA_FIN`   	VARCHAR(5) NOT NULL,
   PRIMARY KEY(`ID_HORARIO`)
);
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('11:00', '12:00');
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('12:00', '13:00');
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('13:00', '14:00');
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('14:00', '15:30');
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('18:00', '19:00');
INSERT INTO HORARIOS (HORA_INI, HORA_FIN) VALUES ('19:00', '20:30');


/* 21/02/2016 */
ALTER TABLE PEDIDOS  MODIFY COLUMN `FECHA_FACTURA` DATETIME;
ALTER TABLE PEDIDOS  MODIFY COLUMN `FECHA_ENTREGA` DATETIME;

ALTER TABLE PEDIDOS  ADD COLUMN `NUM_ALBARAN_ANUAL` INTEGER(8);
ALTER TABLE PEDIDOS  ADD COLUMN `NUM_FACTURA_ANUAL` INTEGER(6);
ALTER TABLE PEDIDOS  ADD COLUMN `VERDE` BOOLEAN DEFAULT '0' NOT NULL;

/*24/07/2016*/
ALTER TABLE CLASE_PRODUCTO  ADD COLUMN `COD_CLASE_PRODUCTO` VARCHAR(3);
ALTER TABLE `PRODUCTOS` CHANGE `ID_CLASE_PRODUCTO` `ID_CLASE_PRODUCTO` INT(10) NOT NULL DEFAULT '-1';

INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (0	,0	, NULL, NULL, 1, 'TRANSPORTE', 'TRP');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (1	,1	, NULL, NULL, 1, 'RAÍZ', 'RA');
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (2	,2	, NULL, NULL, 1, 'FRUTA DE CÁSCARA', 'FRC');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (3	,3	, NULL, NULL, 1, 'FLOR', 'FLO');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (4	,4	, NULL, NULL, 1, 'GRANEL', 'GRA');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (5	,5	, NULL, NULL, 1, 'CRISTAL ', 'CRI');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (6	,6	, NULL, NULL, 1, 'ENVASADO', 'ENV');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (7	,7	, NULL, NULL, 1, 'PANES', 'PAN');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (8	,8	, NULL, NULL, 1, 'FRUTO', 'FRU');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (9	,9	, NULL, NULL, 1, 'FRUTA DE PIEL', 'FRP');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (10	,10	, NULL, NULL, 1, 'HOJA', 'HO');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (11	,11	, NULL, NULL, 1, 'FRÁGIL', 'FRA');	
INSERT INTO CLASE_PRODUCTO (`ID_CLASE_PRODUCTO`, `SECUENCIA`, `ID_CATEGORIA`, `ID_SUBCATEGORIA`, `ACTIVO`, `DESCRIPCION`, `COD_CLASE_PRODUCTO`) VALUES (12	,12	, NULL, NULL, 1, 'REFRIGERADO', 'REF');	




COMMIT;

